CACHE_MODE: False
DATASET:
  COCO_PANOPTIC_PATH: None
  DATASET_FILE: HRRSD_to_SSDD
  DA_MODE: uda
  NUM_CLASSES: 2
  REMOVE_DIFFICULT: False
DEVICE: cuda
DIST:
  DISTRIBUTED: True
  DIST_BACKEND: nccl
  DIST_URL: env://
  GPU: 0
  RANK: 0
  WORLD_SIZE: 4
EVAL: False
LOSS:
  FOCAL_LOSS: False  
  AUX_LOSS: True
  BACKBONE_LOSS_COEF: 0.1 
  BBOX_LOSS_COEF: 5.0
  CLS_LOSS_COEF: 2.0
  DA_GAMMA: 2
  DICE_LOSS_COEF: 1.0
  FOCAL_ALPHA: 0.25
  GIOU_LOSS_COEF: 2.0
  MASK_LOSS_COEF: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_CLASS: 2.0
  SET_COST_GIOU: 2.0

MODEL:
  BACKBONE: resnet50
  BACKBONE_ALIGN: True 
  DEC_LAYERS: 6
  DEC_N_POINTS: 4
  DILATION: False
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  ENC_LAYERS: 6
  ENC_N_POINTS: 4
  FROZEN_WEIGHTS: None
  HIDDEN_DIM: 256
  MASKS: False
  NHEADS: 8
  NUM_FEATURE_LEVELS: 4
  NUM_QUERIES: 300
  POSITION_EMBEDDING: sine
  POSITION_EMBEDDING_SCALE: 6.283185307179586
  TWO_STAGE: True
  WITH_BOX_REFINE: True

SSOD:
  burn_epochs: 50  #开始应用半监督训练
  cosine_ema: True
  ema_rate: 0.90
  teacher_loss_weight: 3
  thoushold_value: 0.5
  adaptive_thoushold: True #自适应阈值
  strong_aug: True #使用强增广
  RESUME_EMA:

NUM_WORKERS: 12
OUTPUT_DIR: exps/HRRSD_to_SSDD/result
RESUME:
SEED: 42
START_EPOCH: 0
TRAIN:
  BATCH_SIZE: 4
  CLIP_MAX_NORM: 0.1
  EPOCHS: 60
  LR: 0.0002
  LR_BACKBONE: 2e-05
  LR_BACKBONE_NAMES: ['backbone.0']
  LR_DROP: 40
  LR_DROP_EPOCHS: None
  LR_LINEAR_PROJ_MULT: 0.1
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  SGD: False
  WEIGHT_DECAY: 0.0001
